[package]
name = "server"
version = "0.2.8"
authors = ["Zhiyuan Zheng <zhzy0077@hotmail.com>"]
edition = "2018"
repository = "https://github.com/zhzy0077/PipeHub"

[dependencies]
actix-cors = "0.2"
actix-files = "0.2"
actix-http = { version = "1.0", features = ["openssl", "compress"], default-features = false }
actix-rt = "1.1"
actix-session = "0.3"
actix-threadpool = "0.3"
actix-web = "2.0"
appinsights = { git = "https://github.com/zhzy0077/appinsights-rs", rev = "8d5b281" }
async-trait = "0.1"
base58 = "0.1"
chrono = "0.4"
config = "0.10"
# Use preview version that is lock-free.
dashmap = "4.0.0-rc6"
diesel = { version = "1.4", features = ["postgres", "r2d2"] }
diesel_migrations = "1.4"
dotenv = "0.15"
futures-util = "0.3"
lazy_static = "1.4"
log = { version="0.4", features = ["serde", "std"], default-features = false }
num_cpus = "1.13"
openssl = "*"
openssl-probe = "0.1"
r2d2 = "0.8"
rand = "0.7"
reqwest = { version = "0.10", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simplelog = "0.8"
sqlx = { version = "0.3", features = [ "runtime-tokio", "macros", "postgres" ], default-features = false }
tokio = { version = "0.3", features = ["full"] }
url = "2.1"
uuid = { version = "0.8", features = ["v4", "serde"] }
