[package]
name = "server"
version = "0.1.0"
authors = ["Zhiyuan Zheng <zhzy0077@hotmail.com>"]
edition = "2018"
repository = "https://github.com/zhzy0077/PipeHub"

[dependencies]
actix-files = "0.2"
actix-http = { version = "1.0", features = ["openssl", "compress"], default-features = false }
actix-rt = "1.1"
actix-session = "0.3"
actix-threadpool = "0.3"
actix-web = "2.0"
appinsights = "0.1"
async-trait = "0.1"
awc = "1.0"
base58 = "0.1"
config = "0.10"
diesel = { version = "1.4", features = ["postgres", "r2d2"] }
diesel_migrations = "1.4"
dotenv = "0.15"
log = { version="0.4", features = ["serde", "std"], default-features = false }
oauth2 = "2.0"
openssl = "*"
openssl-probe = "0.1"
r2d2 = "0.8"
rand = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simplelog = "0.8"
url = "1.7"
uuid = {version = "0.8", features = ["v4"]}
